### ISSUE TITLE
How much space do i need for the preprocessing task?

### ISSUE THREAD

**Issue by mosszhd** [VITA-Group/AutoSpeech#16]
Hi, I am preprocessing the audio files and it is taking too much space. More than 200 GB and my SSD is getting full every time. Can you tell me how much space I need for preprocessing the dataset?

**Comment by gautam9595** [comment]
Around 350 - 400GB as far as I remember, you can reduce this by filtering out more nationality person. In the data_object/preprocess.py, you have the 'anglophone_nationalites' list which filters the voices from these nationalities only.

**Comment by mosszhd** [comment]
> 

Thanks a lot.
