### ISSUE TITLE
Issue with README

### ISSUE THREAD

**Issue by free-soellingeraj** [VITA-Group/AutoSpeech#4]
I found that the documented directory structure in the master/README.md did not run with the code.  

Where it says:
```
The data should be organized as:

VoxCeleb1
 - wav
 - vox1_meta.csv
 - iden_split.txt
 - veri_test.txt
```
It should say:
```
The data should be organized as:

VoxCeleb1
 - dev/wav/...
 - test/wav/...
 - vox1_meta.csv
 - iden_split.txt
 - veri_test.txt
```

**Comment by shaojinding** [comment]
fixed at https://github.com/VITA-Group/AutoSpeech/commit/9247eceac1b5649089287f49c7610071e3d12e78
