### ISSUE TITLE
TypeError: type object argument after * must be an iterable, not property

### ISSUE THREAD

**Issue by jackNhat** [VITA-Group/AutoSpeech#6]
Thanks for sharing repository,
I tried following the Quick start guideline.
When I ran the command for training from scratch for verification:
`python train_verification.py --cfg exps/scratch/scratch.yaml --text_arch Genotype` and got the error message `TypeError: type object argument after * must be an iterable, not property`. Error highlight in line 21 of `models/model.py`: `op_names, indices = zip(*genotype.normal)`
How to resolve?
Thanks for the reply

**Comment by shaojinding** [comment]
You will need to substitute `GENOTYPE` with the actual object:

`python train_verification.py --cfg exps/scratch/scratch.yaml --text_arch "Genotype(normal=[('dil_conv_5x5', 1), ('dil_conv_3x3', 0), ('dil_conv_5x5', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 1), ('sep_conv_3x3', 2), ('dil_conv_3x3', 2), ('max_pool_3x3', 1)], normal_concat=range(2, 6), reduce=[('max_pool_3x3', 1), ('max_pool_3x3', 0), ('dil_conv_5x5', 2), ('max_pool_3x3', 1), ('dil_conv_5x5', 3), ('dil_conv_3x3', 2), ('dil_conv_5x5', 4), ('dil_conv_5x5', 2)], reduce_concat=range(2, 6))"`
